apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: electromart
type: Opaque
data:
  # Base64 encoded secrets (change these in production)
  MONGODB_PASSWORD: cGFzc3dvcmQ=   # password
  SMTP_PASSWORD: eW91ci1hcHAtcGFzc3dvcmQ=  # your-app-password
  TWILIO_ACCOUNT_SID: eW91cl90d2lsaW9fYWNjb3VudF9zaWQ=  # your_twilio_account_sid
  TWILIO_AUTH_TOKEN: eW91cl90d2lsaW9fYXV0aF90b2tlbg==  # your_twilio_auth_token
