# Shared Redis Deployment for Multiple Services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-redis
  namespace: electromart
  labels:
    app: shared-redis
    type: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-redis
  template:
    metadata:
      labels:
        app: shared-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --appendonly
        - yes
        volumeMounts:
        - name: shared-redis-storage
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: shared-redis-storage
        persistentVolumeClaim:
          claimName: shared-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shared-redis
  namespace: electromart
  labels:
    app: shared-redis
    type: shared
spec:
  selector:
    app: shared-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-redis-pvc
  namespace: electromart
  labels:
    type: shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
