global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Search Service
  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend (if metrics are available)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Database monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
