apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: electromart
  labels:
    app: user-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
      - name: user-service
        image: electromart/user-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: USER_SERVICE_PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: MONGODB_URI
        - name: MONGODB_USER
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: MONGODB_USER
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: JWT_EXPIRES_IN
        - name: BCRYPT_ROUNDS
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: BCRYPT_ROUNDS
        - name: MAX_LOGIN_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: MAX_LOGIN_ATTEMPTS
        - name: LOCKOUT_DURATION
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: LOCKOUT_DURATION
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_SECRET
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: MONGODB_PASSWORD
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: electromart
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
