apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: electromart
data:
  # API Gateway Configuration
  API_GATEWAY_PORT: "8000"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8002"
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_SERVICE_URL: "http://order-service:8003"
  PAYMENT_SERVICE_URL: "http://payment-service:8004"
  SEARCH_SERVICE_URL: "http://search-service:8005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8006"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Monitoring
  PROMETHEUS_ENDPOINT: "http://prometheus:9090"
