apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: electromart
  labels:
    app: search-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
        version: v1
    spec:
      containers:
      - name: search-service
        image: electromart/search-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: search-service-config
              key: SEARCH_SERVICE_PORT
        - name: ELASTICSEARCH_URL
          valueFrom:
            configMapKeyRef:
              name: search-service-config
              key: ELASTICSEARCH_URL
        - name: ELASTICSEARCH_USER
          valueFrom:
            configMapKeyRef:
              name: search-service-config
              key: ELASTICSEARCH_USER
        - name: ELASTICSEARCH_INDEX
          valueFrom:
            configMapKeyRef:
              name: search-service-config
              key: ELASTICSEARCH_INDEX
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: search-service-secrets
              key: ELASTICSEARCH_PASSWORD
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: search-service-config
              key: REDIS_URL
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: electromart
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
  type: ClusterIP
