apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: electromart
  labels:
    app: order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: v1
    spec:
      containers:
      - name: order-service
        image: electromart/order-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: ORDER_SERVICE_PORT
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: POSTGRES_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-service-secrets
              key: POSTGRES_PASSWORD
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: USER_SERVICE_URL
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: PRODUCT_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: PAYMENT_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: NOTIFICATION_SERVICE_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: electromart
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP
