apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: electromart
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
      - name: payment-service
        image: electromart/payment-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: PAYMENT_SERVICE_PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: REDIS_URL
        - name: STRIPE_CURRENCY
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: STRIPE_CURRENCY
        - name: STRIPE_WEBHOOK_PATH
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: STRIPE_WEBHOOK_PATH
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payment-service-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-service-secrets
              key: STRIPE_WEBHOOK_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: electromart
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
  type: ClusterIP
